In [1]:
import pandas as pd
import numpy as np
import math
import operator
from itertools import combinations

In [2]:
def subsets(s):
    sets = []
    for i in range(1 << len(s)):
        subset = [s[bit] for bit in range(len(s)) if is_bit_set(i, bit)]
        sets.append(subset)
    return sets

def halfsubsets(s):
    sets = []
    for i in range(1 << len(s)):
        subset = [s[bit] for bit in range(len(s)) if is_bit_set(i, bit)]
        if(len(subset) <= len(s)/2):
            sets.append(subset)
    return sets

def is_bit_set(num, bit):
    return num & (1 << bit) > 0

# Load CSV Data

In [3]:
df = pd.read_csv('TestSample_100_XTable.csv')
del df['Unnamed: 0']

## Step 1. Create cut info

In [4]:
unique_X0 = sorted((df['Cont1']+1).unique())
unique_X1 = sorted((df['Cont2']+1).unique())
unique_X2 = sorted((df['Cont3']+1).unique())
unique_X3 = sorted((df['Ord1']+1).unique())
unique_X4 = sorted((df['Ord2']+1).unique())
unique_X5 = sorted((df['Ord3']+1).unique())
unique_X6 = sorted(df['Nom1'].unique())
sets_X6 = halfsubsets(unique_X6)
unique_X7 = sorted(df['Nom2'].unique())
sets_X7 = halfsubsets(unique_X7)
unique_X8 = sorted(df['Nom3'].unique())
sets_X8 = halfsubsets(unique_X8)

In [5]:
var = [0,1,2,3,4,5,6,7,8]
var_comb = list(combinations(var,3))
var_info = pd.DataFrame(var_comb)
var_info.columns = ['var i','var j','var k']
var_info

    var i  var j  var k
0       0      1      2
1       0      1      3
2       0      1      4
3       0      1      5
4       0      1      6
5       0      1      7
6       0      1      8
7       0      2      3
8       0      2      4
9       0      2      5
10      0      2      6
11      0      2      7
12      0      2      8
13      0      3      4
14      0      3      5
15      0      3      6
16      0      3      7
17      0      3      8
18      0      4      5
19      0      4      6
20      0      4      7
21      0      4      8
22      0      5      6
23      0      5      7
24      0      5      8
25      0      6      7
26      0      6      8
27      0      7      8
28      1      2      3
29      1      2      4
..    ...    ...    ...
54      2      4      5
55      2      4      6
56      2      4      7
57      2      4      8
58      2      5      6
59      2      5      7
60      2      5      8
61      2      6      7
62      2      6      8
63      2      7      8
64      3      4      5
65      3      4      6
66      3      4      7
67      3      4      8
68      3      5      6
69      3      5      7
70      3      5      8
71      3      6      7
72      3      6      8
73      3      7      8
74      4      5      6
75      4      5      7
76      4      5      8
77      4      6      7
78      4      6      8
79      4      7      8
80      5      6      7
81      5      6      8
82      5      7      8
83      6      7      8

[84 rows x 3 columns]

In [6]:
len(var_info)

84

## Step 2. Search

### Case 1. var0, var 1 and var2 (Cont 1, Cont 2, and Cont 3)

In [7]:
Results = []
ResultsIndex = []
for i in unique_X0:
    for j in unique_X1:
        for k in unique_X2:
            X_Search = df.copy()[['Cont1','Cont2','Cont3','A','Y']];
            X_Search['C1'] = df['Cont1'].apply(lambda x : 1 if x<i else 0)
            X_Search['C2'] = df['Cont2'].apply(lambda x : 1 if x<j else 0)
            X_Search['C3'] = df['Cont3'].apply(lambda x : 1 if x<k else 0)
            X_Search['D1'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==1)&(row['C3']==1) else 0, axis=1)
            X_Search['D2'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==1)&(row['C3']==0) else 0, axis=1)
            X_Search['D3'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==0)&(row['C3']==1) else 0, axis=1)
            X_Search['D4'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==0)&(row['C3']==0) else 0, axis=1)
            X_Search['D5'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==1)&(row['C3']==1) else 0, axis=1)
            X_Search['D6'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==1)&(row['C3']==0) else 0, axis=1)
            X_Search['D7'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==0)&(row['C3']==1) else 0, axis=1)
            X_Search['D8'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==0)&(row['C3']==0) else 0, axis=1)
            X_Search['E1'] = np.where(X_Search['D1']==X_Search['A'], 1, 0)
            X_Search['E2'] = np.where(X_Search['D2']==X_Search['A'], 1, 0)
            X_Search['E3'] = np.where(X_Search['D3']==X_Search['A'], 1, 0)
            X_Search['E4'] = np.where(X_Search['D4']==X_Search['A'], 1, 0)
            X_Search['E5'] = np.where(X_Search['D5']==X_Search['A'], 1, 0)
            X_Search['E6'] = np.where(X_Search['D6']==X_Search['A'], 1, 0)
            X_Search['E7'] = np.where(X_Search['D7']==X_Search['A'], 1, 0)
            X_Search['E8'] = np.where(X_Search['D8']==X_Search['A'], 1, 0)
            E_X_Search_1 = sum(X_Search['Y']*X_Search['E1'])*2/df.shape[0]
            E_X_Search_2 = sum(X_Search['Y']*X_Search['E2'])*2/df.shape[0]
            E_X_Search_3 = sum(X_Search['Y']*X_Search['E3'])*2/df.shape[0]
            E_X_Search_4 = sum(X_Search['Y']*X_Search['E4'])*2/df.shape[0]
            E_X_Search_5 = sum(X_Search['Y']*X_Search['E5'])*2/df.shape[0]
            E_X_Search_6 = sum(X_Search['Y']*X_Search['E6'])*2/df.shape[0]
            E_X_Search_7 = sum(X_Search['Y']*X_Search['E7'])*2/df.shape[0]
            E_X_Search_8 = sum(X_Search['Y']*X_Search['E8'])*2/df.shape[0]
            E = [E_X_Search_8,E_X_Search_7,E_X_Search_6,E_X_Search_5,E_X_Search_4,E_X_Search_3,E_X_Search_2,E_X_Search_1]
            index, value = max(enumerate(E), key=operator.itemgetter(1))
            Results.append(value)
            ResultsIndex.append(index)

In [8]:
index, value = max(enumerate(Results), key=operator.itemgetter(1))
print("cut index: "+str(index//100+1)+' '+str((index%100)//10+1)+' '+str(index%10+1))
print("max: "+str(value))
print("dir: "+str(ResultsIndex[index]))

cut index: 10 5 2
max: 63.805154
dir: 6

### Case 2. var3, var 4 and var5 (Ord 1, Ord 2, and Ord 3)

In [9]:
Results = []
ResultsIndex = []
for i in unique_X3:
    for j in unique_X4:
        for k in unique_X5:
            X_Search = df.copy()[['Ord1','Ord2','Ord3','A','Y']];
            X_Search['C1'] = df['Ord1'].apply(lambda x : 1 if x<i else 0)
            X_Search['C2'] = df['Ord2'].apply(lambda x : 1 if x<j else 0)
            X_Search['C3'] = df['Ord3'].apply(lambda x : 1 if x<k else 0)
            X_Search['D1'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==1)&(row['C3']==1) else 0, axis=1)
            X_Search['D2'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==1)&(row['C3']==0) else 0, axis=1)
            X_Search['D3'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==0)&(row['C3']==1) else 0, axis=1)
            X_Search['D4'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==0)&(row['C3']==0) else 0, axis=1)
            X_Search['D5'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==1)&(row['C3']==1) else 0, axis=1)
            X_Search['D6'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==1)&(row['C3']==0) else 0, axis=1)
            X_Search['D7'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==0)&(row['C3']==1) else 0, axis=1)
            X_Search['D8'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==0)&(row['C3']==0) else 0, axis=1)
            X_Search['E1'] = np.where(X_Search['D1']==X_Search['A'], 1, 0)
            X_Search['E2'] = np.where(X_Search['D2']==X_Search['A'], 1, 0)
            X_Search['E3'] = np.where(X_Search['D3']==X_Search['A'], 1, 0)
            X_Search['E4'] = np.where(X_Search['D4']==X_Search['A'], 1, 0)
            X_Search['E5'] = np.where(X_Search['D5']==X_Search['A'], 1, 0)
            X_Search['E6'] = np.where(X_Search['D6']==X_Search['A'], 1, 0)
            X_Search['E7'] = np.where(X_Search['D7']==X_Search['A'], 1, 0)
            X_Search['E8'] = np.where(X_Search['D8']==X_Search['A'], 1, 0)
            E_X_Search_1 = sum(X_Search['Y']*X_Search['E1'])*2/df.shape[0]
            E_X_Search_2 = sum(X_Search['Y']*X_Search['E2'])*2/df.shape[0]
            E_X_Search_3 = sum(X_Search['Y']*X_Search['E3'])*2/df.shape[0]
            E_X_Search_4 = sum(X_Search['Y']*X_Search['E4'])*2/df.shape[0]
            E_X_Search_5 = sum(X_Search['Y']*X_Search['E5'])*2/df.shape[0]
            E_X_Search_6 = sum(X_Search['Y']*X_Search['E6'])*2/df.shape[0]
            E_X_Search_7 = sum(X_Search['Y']*X_Search['E7'])*2/df.shape[0]
            E_X_Search_8 = sum(X_Search['Y']*X_Search['E8'])*2/df.shape[0]
            E = [E_X_Search_8,E_X_Search_7,E_X_Search_6,E_X_Search_5,E_X_Search_4,E_X_Search_3,E_X_Search_2,E_X_Search_1]
            index, value = max(enumerate(E), key=operator.itemgetter(1))
            Results.append(value)
            ResultsIndex.append(index)

In [10]:
index, value = max(enumerate(Results), key=operator.itemgetter(1))
print("cut index: "+str(index//125+1)+' '+str((index%125)//5+1)+' '+str(index%5+1))
print("max: "+str(value))
print("dir: "+str(ResultsIndex[index]))

cut index: 1 4 4
max: 61.4430054
dir: 5

### Case 3. var6, var 7 and var8 (Nom 1, Nom 2, and Nom 3)

In [16]:
Results = []
ResultsIndex = []
for i in range(len(sets_X6)):
    for j in range(len(sets_X7)):
        for k in range(len(sets_X8)):
            X_Search = df.copy()[['Nom1','Nom2','Nom3','A','Y']];
            X_Search['C1'] = df['Nom1'].apply(lambda x : 1 if x in sets_X6[i] else 0)
            X_Search['C2'] = df['Nom2'].apply(lambda x : 1 if x in sets_X7[j] else 0)
            X_Search['C3'] = df['Nom3'].apply(lambda x : 1 if x in sets_X8[k] else 0)
            X_Search['D1'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==1)&(row['C3']==1) else 0, axis=1)
            X_Search['D2'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==1)&(row['C3']==0) else 0, axis=1)
            X_Search['D3'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==0)&(row['C3']==1) else 0, axis=1)
            X_Search['D4'] = X_Search.apply(lambda row: 1 if (row['C1']==1)&(row['C2']==0)&(row['C3']==0) else 0, axis=1)
            X_Search['D5'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==1)&(row['C3']==1) else 0, axis=1)
            X_Search['D6'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==1)&(row['C3']==0) else 0, axis=1)
            X_Search['D7'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==0)&(row['C3']==1) else 0, axis=1)
            X_Search['D8'] = X_Search.apply(lambda row: 1 if (row['C1']==0)&(row['C2']==0)&(row['C3']==0) else 0, axis=1)
            X_Search['E1'] = np.where(X_Search['D1']==X_Search['A'], 1, 0)
            X_Search['E2'] = np.where(X_Search['D2']==X_Search['A'], 1, 0)
            X_Search['E3'] = np.where(X_Search['D3']==X_Search['A'], 1, 0)
            X_Search['E4'] = np.where(X_Search['D4']==X_Search['A'], 1, 0)
            X_Search['E5'] = np.where(X_Search['D5']==X_Search['A'], 1, 0)
            X_Search['E6'] = np.where(X_Search['D6']==X_Search['A'], 1, 0)
            X_Search['E7'] = np.where(X_Search['D7']==X_Search['A'], 1, 0)
            X_Search['E8'] = np.where(X_Search['D8']==X_Search['A'], 1, 0)
            E_X_Search_1 = sum(X_Search['Y']*X_Search['E1'])*2/df.shape[0]
            E_X_Search_2 = sum(X_Search['Y']*X_Search['E2'])*2/df.shape[0]
            E_X_Search_3 = sum(X_Search['Y']*X_Search['E3'])*2/df.shape[0]
            E_X_Search_4 = sum(X_Search['Y']*X_Search['E4'])*2/df.shape[0]
            E_X_Search_5 = sum(X_Search['Y']*X_Search['E5'])*2/df.shape[0]
            E_X_Search_6 = sum(X_Search['Y']*X_Search['E6'])*2/df.shape[0]
            E_X_Search_7 = sum(X_Search['Y']*X_Search['E7'])*2/df.shape[0]
            E_X_Search_8 = sum(X_Search['Y']*X_Search['E8'])*2/df.shape[0]
            E = [E_X_Search_8,E_X_Search_7,E_X_Search_6,E_X_Search_5,E_X_Search_4,E_X_Search_3,E_X_Search_2,E_X_Search_1]
            index, value = max(enumerate(E), key=operator.itemgetter(1))
            Results.append(value)
            ResultsIndex.append(index)

In [18]:
index, value = max(enumerate(Results), key=operator.itemgetter(1))
print("cut index: "+str(index//256)+' '+str((index%256)//16)+' '+str(index%16))
print("max: "+str(value))
print("dir: "+str(ResultsIndex[index]))

cut index: 5 14 8
max: 63.7606934
dir: 2